apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "milvus.fullname" . }}
data:
  default.yaml: |+
    {{- include "milvus.config" . | nindent 4 }}

{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- if or .Values.logstore.enabled .Values.externalLogstore.enabled }}
  logstore.yaml: |+
    {{- include "milvus.logstore.config" . | nindent 4 }}
{{- end }}
